apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-k8s-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-k8s-app
  template:
    metadata:
      labels:
        app: java-k8s-app
    spec:
      imagePullSecrets:
        - name: acr-secret
      volumes:
        - name: config-volume
          configMap:
            name: dropwizard-config   # Must match ConfigMap name
      containers:
        - name: java-k8s-app
          image: image: javaemo.azurecr.io/productcatalogue:31
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /app/config.yml
              subPath: config.yml
