apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-k8s-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-k8s-app
  template:
    metadata:
      labels:
        app: java-k8s-app
    spec:
      containers:
      - name: java-k8s-app
        image: REPLACE_IMAGE
        ports:
        - containerPort: 8080
